version: "3"

services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile.vault
    container_name: vault
    ports:
      - 8200:8200
    restart: always
    volumes:
      - ${VAULT_CONFIG_PATH}:/vault/config
      - ${VAULT_POLICIES_PATH}:/vault/policies
      - ${VAULT_DATA_PATH}:/vault/data
      - ${VAULT_LOGS_PATH}:/vault/logs
      - ${VAULT_SSL_PATH}:/vault/ssl
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_CACERT=${VAULT_CACERT}
      - VAULT_CLIENT_KEY=${VAULT_CLIENT_KEY}
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    networks:
      - vault-network

networks:
  vault-network: